import { createServerRunner } from "@aws-amplify/adapter-nextjs";
// Generated by `npx ampx sandbox` locally and by the Amplify build for deployed branches.
import outputs from "../../../amplify_outputs.json";

export { outputs };
export const { runWithAmplifyServerContext } = createServerRunner({ config: outputs });
