// Every fixed label a guest can see, in English and Hindi.
export const UI = {
  weddingOf: { en: "The wedding of", hi: "शुभ विवाह" },
  together: { en: "Together with their families", hi: "अपने परिवारों के साथ" },
  saveTheDate: { en: "Save the Date", hi: "तिथि याद रखें" },
  countdown: { en: "Counting down", hi: "शुभ घड़ी की प्रतीक्षा" },
  days: { en: "Days", hi: "दिन" },
  hours: { en: "Hours", hi: "घंटे" },
  minutes: { en: "Minutes", hi: "मिनट" },
  seconds: { en: "Seconds", hi: "सेकंड" },
  begun: { en: "The celebrations have begun!", hi: "उत्सव आरंभ हो चुका है!" },
  venue: { en: "Venue", hi: "स्थल" },
  openMap: { en: "Open in Google Maps", hi: "गूगल मैप्स में देखें" },
  travel: { en: "Getting there", hi: "कैसे पहुँचें" },
  schedule: { en: "Celebrations", hi: "कार्यक्रम" },
  dressCode: { en: "Dress code", hi: "पोशाक" },
  addToCalendar: { en: "Add to Google Calendar", hi: "गूगल कैलेंडर में जोड़ें" },
  downloadIcs: { en: "Download (.ics)", hi: "डाउनलोड (.ics)" },
  gallery: { en: "Our moments", hi: "हमारे पल" },
  film: { en: "The invitation film", hi: "निमंत्रण फ़िल्म" },
  rsvp: { en: "RSVP", hi: "उपस्थिति की पुष्टि" },
  rsvpBy: { en: "Kindly respond by", hi: "कृपया उत्तर दें" },
  rsvpClosed: { en: "RSVPs closed on", hi: "उत्तर देने की अंतिम तिथि थी" },
  rsvpContact: { en: "For changes, please contact the family:", hi: "बदलाव के लिए परिवार से संपर्क करें:" },
  rsvpPreview: { en: "RSVP opens once this invitation is published.", hi: "निमंत्रण प्रकाशित होने पर उत्तर दे सकेंगे।" },
  rsvpFailed: { en: "Something went wrong. Please try again.", hi: "कुछ गड़बड़ हुई। कृपया फिर से प्रयास करें।" },
  name: { en: "Name", hi: "नाम" },
  phone: { en: "Phone", hi: "फ़ोन" },
  attending: { en: "Will you join us?", hi: "क्या आप पधारेंगे?" },
  yes: { en: "Joyfully accept", hi: "सहर्ष स्वीकार" },
  no: { en: "Regretfully decline", hi: "खेद सहित अस्वीकार" },
  maybe: { en: "Not sure yet", hi: "अभी तय नहीं" },
  guests: { en: "Number of guests", hi: "अतिथियों की संख्या" },
  whichEvents: { en: "Which celebrations will you attend?", hi: "आप किन कार्यक्रमों में आएँगे?" },
  meal: { en: "Meal preference", hi: "भोजन वरीयता" },
  mealVeg: { en: "Vegetarian", hi: "शाकाहारी" },
  mealNonVeg: { en: "Non-vegetarian", hi: "मांसाहारी" },
  mealJain: { en: "Jain", hi: "जैन" },
  message: { en: "Message for the couple", hi: "दंपति के लिए संदेश" },
  submit: { en: "Send RSVP", hi: "उत्तर भेजें" },
  sending: { en: "Sending…", hi: "भेजा जा रहा है…" },
  thanks: { en: "Thank you! Your response has been received.", hi: "धन्यवाद! आपका उत्तर मिल गया है।" },
  closing: { en: "With best compliments from", hi: "शुभाकांक्षी" },
  share: { en: "Share on WhatsApp", hi: "व्हाट्सऐप पर भेजें" },
  tapToOpen: { en: "Tap to open", hi: "खोलने के लिए टैप करें" },
  scratchHint: { en: "Scratch to reveal the date", hi: "तिथि देखने के लिए खुरचें" },
  revealNow: { en: "or tap here", hi: "या यहाँ टैप करें" },
  scrollToOpen: { en: "Scroll to open", hi: "खोलने के लिए स्क्रॉल करें" },
  credit: { en: "Created by Baba Saab Events", hi: "बाबा साब इवेंट्स द्वारा निर्मित" },
  errors: {
    required: { en: "This field is required", hi: "यह आवश्यक है" },
    phone: { en: "Enter a valid phone number", hi: "सही फ़ोन नंबर दर्ज करें" },
    count: { en: "Enter a number from 1 to 20", hi: "1 से 20 के बीच संख्या दर्ज करें" },
  },
};
